version: '3.8'
services:
  web:
    image: ghcr.io/universityradioyork/myradio:master
    expose: ['80']
    env_file: stack.env
    networks: [urynet]

networks:
  urynet:
    name: urynet
    external: true
