version: '3.8'
services:
  web:
    image: registry.ury.org.uk/myradio:2022-09-23-001
    expose: ['80']
    env_file: stack.env
    networks: [urynet]

networks:
  urynet:
    name: urynet
    external: true
