networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:2a756b824d40f6a7a4f82ce9df9d413dc9dd69c7
    networks:
    - urynet
version: '3.8'
