networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:655ad8b2ee35a82a6b447df64af506f41e22bab4
    networks:
    - urynet
version: '3.8'
