networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:b759efce72ed67ce22e826144b66ac2cead6ef67
    networks:
    - urynet
version: '3.8'
