networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:79609a7642a19ce7321e534a00627da4387285dc
    networks:
    - urynet
version: '3.8'
