networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:3a352818f0c0e41629e92b2d586bbb4be7c0208b
    networks:
    - urynet
version: '3.8'
