networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:660d48b64c2e27f96af8ecd4dc8f587e11bc4afd
    networks:
    - urynet
version: '3.8'
