networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: registry.ury.org.uk/myradio:2022-09-23-001
    networks:
    - urynet
version: '3.8'
