networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:132941da756fb6a2311e442376721529ba0e4317
    networks:
    - urynet
version: '3.8'
