networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:8f1f789cdd6fd66f15b1a5738f18433ac712e2b8
    networks:
    - urynet
version: '3.8'
