networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:d4a2ee894de67ff0d8943b5a2eec5df893875007
    networks:
    - urynet
version: '3.8'
