networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:bf7c446adbdc99a8619500177d862ddbc73a9069
    networks:
    - urynet
version: '3.8'
