networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:9a5cf093faed8e49de339b81303ef7d499738b1e
    networks:
    - urynet
version: '3.8'
