networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:8db99a742bd635419ca2f1d46e94982268e5c986
    networks:
    - urynet
version: '3.8'
