networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:29150f8a2aebc3249c0fea1abf3a316195c233df
    networks:
    - urynet
version: '3.8'
