networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:9cf16a78bbf249682ff55f6f900272dae4ac56c4
    networks:
    - urynet
version: '3.8'
