networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:dee84298de3e66ff6baaad97a492e834729c058b
    networks:
    - urynet
version: '3.8'
