networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:733458714abf756d4e5d35553da37fe20c9839b2
    networks:
    - urynet
version: '3.8'
