networks:
  urynet:
    external: true
    name: urynet
services:
  web:
    env_file: stack.env
    expose:
    - '80'
    image: ghcr.io/universityradioyork/myradio:c8375921329d84d357750ebc3573e0c27c04cb36
    networks:
    - urynet
version: '3.8'
