[tool.poetry]
name = "stacks"
version = "0.1.0"
description = ""
authors = ["Marks Polakovs <marks.polakovs@ury.org.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
PyYAML = "^6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
